### ISSUE TITLE
Adding Airspace - LRBB

### ISSUE THREAD

**Issue by accro6** [ogruetzmann/ModeS#6]
We've now finished our trial of Mode S correlation for LRBB airspace. As such, we would be happy to have it included. It contains all airports starting LR**, (and hopefully LDZO, LHBP and LQSB shortly)
Alex

**Comment by ogruetzmann** [comment]
I'll keep this back for now. It doesn't make sense as long as there's a gap between you and the rest of the airspace. And it looks like I'll need to implement some filter to prevent assignment for traffic passing areas that are not participating.
On the list, but it will take some time.
