### ISSUE TITLE
Adding EPWW

### ISSUE THREAD

**Issue by ThaweK** [ogruetzmann/ModeS#9]
Hello, we'd like to ad an EPWW FIR into plugin. Is it possible? Thanks!

**Comment by ogruetzmann** [comment]
Will be added for next AIRAC

**Comment by ogruetzmann** [comment]
@ThaweK Comment here if you want it added right now :)

**Comment by ThaweK** [comment]
In real life they introduce it since Monday. We need to brief out ATC anyways, so AFAIK new AIRAC is 23APR20 so I think we should be fine ;)

**Comment by ThaweK** [comment]
Can we expect the release, or am I suppose to build project by myself?

**Comment by ogruetzmann** [comment]
I'll issue a release this evening and the new config will be distributed to the old version as well at startup.

**Comment by ogruetzmann** [comment]
Done
